[2025-05-26T15:11:01.631+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task3 scheduled__2025-05-26T07:09:00+00:00 [queued]>
[2025-05-26T15:11:01.636+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task3 scheduled__2025-05-26T07:09:00+00:00 [queued]>
[2025-05-26T15:11:01.637+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-05-26T15:11:01.672+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task3> on 2025-05-26 07:09:00+00:00
[2025-05-26T15:11:01.679+0000] {standard_task_runner.py:57} INFO - Started process 4188 to run task
[2025-05-26T15:11:01.683+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task3', 'scheduled__2025-05-26T07:09:00+00:00', '--job-id', '440', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpdja82y8p']
[2025-05-26T15:11:01.686+0000] {standard_task_runner.py:85} INFO - Job 440: Subtask task3
[2025-05-26T15:11:01.696+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-26T15:11:01.729+0000] {task_command.py:415} INFO - Running <TaskInstance: first_dag.task3 scheduled__2025-05-26T07:09:00+00:00 [running]> on host 4ef62d544527
[2025-05-26T15:11:01.796+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sirtaf' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T07:09:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T07:09:00+00:00'
[2025-05-26T15:11:01.798+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-26T15:11:01.799+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world, this is the third task!']
[2025-05-26T15:11:01.809+0000] {subprocess.py:86} INFO - Output:
[2025-05-26T15:11:01.810+0000] {subprocess.py:93} INFO - Hello world, this is the third task!
[2025-05-26T15:11:01.811+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-26T15:11:01.877+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task3, execution_date=20250526T070900, start_date=20250526T151101, end_date=20250526T151101
[2025-05-26T15:11:01.947+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-26T15:11:01.968+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
