[2025-05-26T15:11:42.284+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task2 scheduled__2025-05-26T13:15:00+00:00 [queued]>
[2025-05-26T15:11:42.288+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task2 scheduled__2025-05-26T13:15:00+00:00 [queued]>
[2025-05-26T15:11:42.289+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-05-26T15:11:42.301+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task2> on 2025-05-26 13:15:00+00:00
[2025-05-26T15:11:42.304+0000] {standard_task_runner.py:57} INFO - Started process 5312 to run task
[2025-05-26T15:11:42.306+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task2', 'scheduled__2025-05-26T13:15:00+00:00', '--job-id', '809', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp57juaomy']
[2025-05-26T15:11:42.309+0000] {standard_task_runner.py:85} INFO - Job 809: Subtask task2
[2025-05-26T15:11:42.325+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-26T15:11:42.362+0000] {task_command.py:415} INFO - Running <TaskInstance: first_dag.task2 scheduled__2025-05-26T13:15:00+00:00 [running]> on host 4ef62d544527
[2025-05-26T15:11:42.448+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sirtaf' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T13:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T13:15:00+00:00'
[2025-05-26T15:11:42.454+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-26T15:11:42.458+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world, this is the second task!']
[2025-05-26T15:11:42.474+0000] {subprocess.py:86} INFO - Output:
[2025-05-26T15:11:42.475+0000] {subprocess.py:93} INFO - Hello world, this is the second task!
[2025-05-26T15:11:42.475+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-26T15:11:42.505+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task2, execution_date=20250526T131500, start_date=20250526T151142, end_date=20250526T151142
[2025-05-26T15:11:42.613+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-26T15:11:42.696+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
